####################################################################################################
# TLS Certificate Manageement
# We need to install an issuer in each namescpace that use CertManager
kind: Issuer  # letsencrypt-prod
apiVersion: cert-manager.io/v1
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: {{ .Values.letsEncrypt.email | quote }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable HTTP01 validations
    solvers:
    - selector: {}
      http01:
        ingress:
          class: traefik
