type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
    name: {{ .Values.imagePullSecrets.mainDockerSource.name }}
kind: Secret
data:
   .dockerconfigjson: {{ .Values.imagePullSecrets.mainDockerSource.dockerConfigJSON }}
