apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mpy13c.fullname" . }}-gui
  labels:
    {{- include "mpy13c.labels" . | nindent 4 }}
    app.kubernetes.io/component: "gui_worker"
spec:
  {{- if not .Values.gui_worker.autoscaling.enabled }}
  replicas: {{ .Values.gui_worker.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mpy13c.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "gui_worker"
  template:
    metadata:
      {{- with .Values.gui_worker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mpy13c.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: gui_worker
    spec:
      imagePullSecrets:
       - name: {{ .Values.imagePullSecrets.mainDockerSource.name | quote }}
      serviceAccountName: {{ include "mpy13c.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: gui-{{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- toYaml .Values.gui_worker.args | nindent 12 }}
          env: 
            {{- toYaml .Values.postgresql_db_env | nindent 12 }}
            {{- toYaml .Values.ikb_options_env | nindent 12 }}
          ports:
            - name: http
              containerPort: 8069
              protocol: TCP
            - name: gevent
              containerPort: 8072
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.gui_worker.resources | nindent 12 }}
      {{- with .Values.gui_worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.gui_worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.gui_worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}