{{- if .Values.imq_worker.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "mpy13c.fullname" . }}-workers
  labels:
    {{- include "mpy13c.labels" . | nindent 4 }}
    app.kubernetes.io/component: "imq_worker"

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "mpy13c.fullname" . }}-workers
  minReplicas: {{ .Values.imq_worker.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.imq_worker.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.imq_worker.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.imq_worker.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.imq_worker.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.imq_worker.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
